
title: Mein Lebenslauf
url: 'http://thomas.czogalik.de'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Thomas Czogalik
tagline: Student (Software Entwickler)
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: kontakt@thomasczogalik.de
phone: 012 345 6789
website: thomasczogalik.de #do not add http://
linkedin: alandoe 
xing: Thomas_Czogalik
github: thomcz
twitter: '@thomczog'


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
