# Site Settings
title: Mein Lebenslauf
url: 'http://thomasczogalik.de'
baseurl: '/online-cv' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
#Profile information
name: Thomas Czogalik
tagline: Student (Informatik)
pic: picture.jpg #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Hallo mein Name ist Thomas Czogalik und ich studiere Informatik (Master) am Karlsruher Institut für Technologie. 
Aufgrund der Erkenntnisse und Erfahrungen, die ich während und außerhalb meines Studiums beim Entwerfen und Implementieren von verschiedenen Software-Projekten gewonnen habe, freue ich mich auf eine
Karriere als Softwareentwickler und der Zusammenarbeit in einem Team. Während meines Studiums und als
studentische Hilfskraft habe ich Kenntnisse in verschiedenen Programmiersprachen, vor allem Java, entwickelt.
Neben der Software-Entwicklung konnte ich auch Erfahrung in der Qualitätssicherung von Software sammeln,
indem ich Build-Prozesse aufgesetzt, Software-Tests geschrieben und Code-Reviews durchgeführt habe.
Auch in meiner Freizeit spielt die Softwareentwicklung eine große Rolle. Immer wieder arbeite ich an privaten
Projekten und probiere neue Technolgien und Programmiersprachen aus. Dabei ist bereits eine Vielzahl von
kleinen Projekten entstanden, die ich auf meiner Github Seite pflege. Außerdem nehme ich an Hackathons
teil, bei denen Teams in wenig Zeit eine innovative Idee entwickeln und umsetzen. Dabei wurde ein Projekt
mit dem ersten Platz ausgezeichnet und ein weiteres Projekt schließlich im Google Play Store veröffentlicht.
Darüber hinaus konnte ich bei Hackathons und Gruppenarbeiten während des Studiums meine Teamfähigkeiten verbessern.'

#sidebar links
email: thomas.czogalik@gmx.de
#phone: 012 345 6789
website: thomasczogalik.de #do not add http://
#linkedin: alandoe 
xing: Thomas_Czogalik
github: thomcz
#twitter: '@thomczog'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: #UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
