# Site Settings
title: Mein Lebenslauf
url: 'http://thomasczogalik.de'
baseurl: '/online-cv' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
#Profile information
name: Thomas Czogalik
tagline: Student (Software Entwickler)
pic: profile.jpg #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Hallo mein Name ist Thomas Czogalik und ich studiere Informatik (Master) am Karlsruher Institut für Technologie. 
Während meines Studiums und meiner Tätigkeit als Wekstudent entwickelte ich ein tiefes Verständnis für Software Design und Entwicklung.
Auch während meiner Freizeit bin ich sehr engagiert mich weiterzubilden. Dazu zählen besuche bei den Karlsruher Entwicklertagen, 
der Microsoft Imagine Conference oder dem Google Developer Fest in Karlsruhe. Regelmäßig besuche ich auch Meetups in Karlsruhe, 
mit Schwerpunkt Softwareentwicklung oder um neue Technologien oder um andere Bereiche kennen zu lernen. 
In meiner Freizeit programmiere ich sehr gerne und probiere auch immer wieder neue Technologien oder Sprachen aus. 
Hin und wieder nehme ich auch mit Freunden an Hackathons teil. 
Bei einem durften wir auch den ersten Platz mit nach Hause nehmen (Microsoft Nikolaus Hackhathon 2016). '

#sidebar links
email: kontakt@thomasczogalik.de
phone: 012 345 6789
website: thomasczogalik.de #do not add http://
linkedin: alandoe 
xing: Thomas_Czogalik
github: thomcz
twitter: '@thomczog'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: #UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
